Unify indentation style in shell scripts
Mixed indentation makes working with the code difficult, as it's
not clear which style to use for new additions. Unify to tabs and adjust
the modelines respectively. For further uniformity, also move all
modelines to the beginning of the files.

Signed-off-by: Georg Pfuetzenreuter <mail@georg-pfuetzenreuter.net>

diff --git a/update-ca-certificates b/update-ca-certificates
--- a/update-ca-certificates
+++ b/update-ca-certificates
@@ -1,4 +1,5 @@
 #!/bin/bash
+# vim:syntax=sh noexpandtab
 #
 # update-ca-certificates
 #
@@ -35,31 +36,31 @@ export statedir
 
 help_and_exit()
 {
-    cat <<-EOF
-	USAGE: $0 [OPTIONS]
-	OPTIONS:
-	  --verbose, -v       verbose output
-	  --root <Directory>  Root directory to use (default: $destdir)
-	  --fresh, -f         start from scratch
-	  --help, -h          this screen
-EOF
-    exit 0
+	cat <<-EOF
+		USAGE: $0 [OPTIONS]
+		OPTIONS:
+		  --verbose, -v       verbose output
+		  --root <Directory>  Root directory to use (default: $destdir)
+		  --fresh, -f         start from scratch
+		  --help, -h          this screen
+	EOF
+	exit 0
 }
 
 args=("$@")
 while [ $# -gt 0 ]; do
-    param="$1"
-    arg="$2"
-    test "$arg" = "${arg#-}" || arg=
-    shift
-    case "$param" in
-	-v|--verbose) verbose='-v' ;;
-	-f|--fresh) fresh='-f' ;;
-	-r|--root) destdir="$arg"; shift
-	    if [ -z "$destdir" ]; then
-		echo "-r option requires parameter <directory>"
-		exit 1
-	    fi
+	param="$1"
+	arg="$2"
+	test "$arg" = "${arg#-}" || arg=
+	shift
+	case "$param" in
+		-v|--verbose) verbose='-v' ;;
+		-f|--fresh) fresh='-f' ;;
+		-r|--root) destdir="$arg"; shift
+		if [ -z "$destdir" ]; then
+			echo "-r option requires parameter <directory>"
+			exit 1
+		fi
 	;;
 	-h|--help) help_and_exit ;;
 	-*) echo "invalid option: $param" >&2; exit 1 ;;
@@ -70,10 +71,10 @@ done
 umask 0222;
 
 case "${TRANSACTIONAL_UPDATE,,*}" in
-    true|yes|1)
-	[ -z "$verbose" ] || echo "transactional update in progress, not running any scripts" >&2
-	> /etc/pki/trust/.updated
-	exit 0
+	true|yes|1)
+		[ -z "$verbose" ] || echo "transactional update in progress, not running any scripts" >&2
+		> /etc/pki/trust/.updated
+		exit 0
 	;;
 esac
 rm -f /etc/pki/trust/.updated
@@ -83,31 +84,31 @@ export destdir
 install -d -m 0755 "$destdir/$statedir"
 # serialize calls if we can
 if [ -z "$_CA_CERTIFICATES_LOCKED" -a -x /usr/bin/flock ]; then
-    export _CA_CERTIFICATES_LOCKED="1"
-    set -- "${args[@]}"
-    exec /usr/bin/flock "$destdir/$statedir" "$0" "$@"
-    echo "failed to lock $destdir/$statedir\n" >&2
-    exit 1
+	export _CA_CERTIFICATES_LOCKED="1"
+	set -- "${args[@]}"
+	exec /usr/bin/flock "$destdir/$statedir" "$0" "$@"
+	echo "failed to lock $destdir/$statedir\n" >&2
+	exit 1
 fi
 
 function find_hooks {
-    shopt -s nullglob
-    for hooksdir in $hooksdir1 $hooksdir2; do
-	for f in "$hooksdir"/*.run; do
-	    if [ -L "$f" ] || [ -f "$f" ]; then
-		echo "${f##*/}" "$f"
-	    fi
+	shopt -s nullglob
+	for hooksdir in $hooksdir1 $hooksdir2; do
+		for f in "$hooksdir"/*.run; do
+			if [ -L "$f" ] || [ -f "$f" ]; then
+				echo "${f##*/}" "$f"
+			fi
+		done
 	done
-    done
 }
 
 while read s f; do
-    if [ -L "$f" -a "`readlink "$f"`" = "/dev/null" ]; then
-	[ -z "$verbose" ] || echo "skipping $f"
-	continue
-    else
-	[ -z "$verbose" ] || echo "running $f .."
-    fi
-    "$f" $fresh $verbose
+	if [ -L "$f" -a "`readlink "$f"`" = "/dev/null" ]; then
+		[ -z "$verbose" ] || echo "skipping $f"
+		continue
+	else
+		[ -z "$verbose" ] || echo "running $f .."
+	fi
+	"$f" $fresh $verbose
 done < <(find_hooks|sort -k 1,1 -u)
 chmod 0555 "$destdir/$statedir"
